name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Command
        # You may pin to the exact commit or the version.
        # uses: D3rHase/ssh-command-action@3d8a11a6823dfe94f4fae068e6fc8b8f3d038c62
        uses: D3rHase/ssh-command-action@v0.2
        with:
          # hostname / IP of the server
          HOST: ${{secrets.BOT_DEPLOY_HOST}}
          # ssh port of the server
          PORT: 22
          # user of the server
          USER: ${{secrets.BOT_DEPLOY_USER}}
          # private ssh key registered on the server
          PRIVATE_SSH_KEY: ${{secrets.BOT_DEPLOY_KEY}}
          # command to be executed
          COMMAND: /home/${{secrets.BOT_DEPLOY_USER}}/deploy_bot
