name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$BOT_DEPLOY_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          BOT_DEPLOY_KEY: ${{secrets.BOT_DEPLOY_KEY}}
          BOT_DEPLOY_USER: ${{secrets.BOT_DEPLOY_USER}}
          BOT_DEPLOY_HOST: ${{secrets.BOT_DEPLOY_HOST}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Run deploy script on VM
        run: ssh -i $SSH_KEY_PATH $BOT_DEPLOY_USER@$BOT_DEPLOY_HOST deploy_bot
